easy_admin:
    site_name: 'RoboTwits'
    entities:
        Users:
            label: 'Пользователи'
            class: App\Entity\Users
            list:
                fields: ['id', 'email', 'roles']
        Page:
            label: 'Страницы'
            class: App\Entity\Page
            controller: App\Controller\Admin\PageController
            list:
                fields: ['id', 'content', 'created']
    design:
        brand_color: 'black'
        menu:
          - Users
          - Page
        assets:
            css:
                - '/bundles/lp/css/lp.css'
