easy_admin:
    site_name: 'RoboTwits'
    entities:
        Users:
            label: 'Пользователи'
            class: App\Entity\Users
            list:
                fields: ['id', 'email', 'roles']
        Page:
            label: 'Страницы'
            class: App\Entity\Page
            controller: App\Controller\Admin\PageController
            list:
                fields: ['id', 'slug']
            form:
                fields:
                    - { type: 'tab' , label: 'Основные' }
                    - { property: 'slug', label: 'Адрес'}
                    - { property: 'content', label: 'Контент', type_options: { block_name: 'page_content' }}

    design:
        brand_color: 'black'
        form_theme:
            - 'admin/form/bootstrap_3_layout.html.twig'
            - 'admin/form/bootstrap_3_horizontal_layout.html.twig'
            - 'admin/form/page_content.html.twig'
        menu:
          - Users
          - Page
        assets:
            css:
                - '/bundles/lp/css/lp.css'
